In [21]:
import numpy as np

Creando una lista de 10 elementos 

In [22]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Transformando lista a un Array

In [23]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Corroborando tipo de estructura 

In [24]:
type(arreglo)

numpy.ndarray

Corroborando el tipo de datos del arreglo 

In [25]:
arreglo.dtype

dtype('int32')

Definiendo el array de int32 a float32

In [26]:
np.array(arreglo, dtype =np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Sigue siendo un array de int32

In [27]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Transformando los datos de int32 a float32

In [28]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Tambien existe una funcion similar a Range pero ocupando arrays 

In [29]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Arreglo de 2 en 2 utilizando arange 

In [30]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2 

array([1, 3, 5, 7, 9])

ALGUNAS FUNCIONES DE NUMPY 

obteniendo el promedio del array 

In [31]:
promedio = np.mean(arreglo)
promedio

5.5

Obteniendo la mediana del array 

In [32]:
mediana = np.median(arreglo)
mediana 

5.5

Desviacion estandar del arreglo 

In [33]:
desviacion_std = np.std(arreglo)
desviacion_std 

2.8722813232690143

Generacion de un arreglo de 10 elementos de solo unos 

In [34]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Generacion de un arreglo de 10 elementos de solo ceros 

In [35]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros 

array([0., 0., 0., 0., 0.])

Transformando el arreglo de unos de punto flotante a enteros 

In [36]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

UTILIZANDO LA FUNCION RANDOM

Generando arreglo aleatorio de 5 elementos 

In [37]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.71539743, 0.54155894, 0.40454492, 0.74842362, 0.05310312,
       0.80489264, 0.51467268, 0.18527328, 0.12109642, 0.39876742])

Generando una Matriz aleatoria de 3x3

In [38]:
matriz = np.random.rand(3,3)
matriz 

array([[0.53329482, 0.5592151 , 0.58424247],
       [0.23654991, 0.83441227, 0.33687981],
       [0.96214333, 0.54707041, 0.74475391]])

Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5 

In [39]:
arreglo_aleatorio2 = np.random.randint(1,1001,5)
arreglo_aleatorio2

array([530, 849, 696, 376, 467])

Generando una Matriz aleatoria de 10 numeros enteros del 1 al 100 

In [40]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[38, 15, 28, 68, 43, 92, 68, 84, 22, 69],
       [80, 94, 17, 61, 84, 10, 10, 77, 24,  3],
       [37, 96, 55, 93, 54, 80, 95, 86, 43, 40],
       [64, 39, 30,  4, 16, 18, 69, 25, 87, 58],
       [52, 91, 35, 66, 62, 30, 46, 48, 79, 80],
       [99, 41, 66, 31, 24,  2, 67, 97, 66, 89],
       [27, 47, 80, 15, 77, 94, 31, 76,  3, 21],
       [ 7, 40, 12, 79, 99, 35, 66, 44, 45, 43],
       [26, 93, 36, 62, 31,  8, 95, 39, 79, 16],
       [75, 85, 37,  5, 21,  1, 34, 61, 99, 48]])